version: '3'

services:
  bot:
    container_name: srcbot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL=${CHANNEL}
      - ADMIN=${ADMIN}
      - CHANNEKS=${CHANNEKS}
      
