version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL=${CHANNEL}
      - ADMIN=${ADMIN}
      - CHANNEKS=${CHANNEKS}
      
